spring:
  application:
    name: yerini-al
  datasource:
    url: jdbc:postgresql://localhost:5432/yerini_al_db
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.95, 0.99

iyzico:
  payment:
    api-key: ${API_KEY}
    secret-key: ${SECRET_KEY}
    base-url: ${BASE_URL}